# TYPE  DATABASE  USER      ADDRESS        METHOD
# El usuario postgres puede conectarse sin contraseña por socket (necesario para initdb y scripts de init)
local   all       tester                 scram-sha-256
local   all       all                 trust

# Todas las demás conexiones requieren contraseña
host   all       tester        0.0.0.0/0         scram-sha-256
host   all       all           0.0.0.0/0      trust
host    all       all       0.0.0.0/0      scram-sha-256
host    all       all       ::/0           scram-sha-256
